export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const INPUT_NAME = 'INPUT_NAME'

export const HANDLE_ERROR = 'HANDLE_ERROR'
